info:
  app:
    name: @project.name@
  description: Config Server
  version: @project.version@

server:
  port: 8000

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../data/properties
        bootstrap: true
        prefix: /

management:
  server:
    port: 9000
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh