name: vault-dev
services:
  vault:
    image: hashicorp/vault:1.18
    ports:
      - "8300:8201"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8201"
      VAULT_DEV_ROOT_TOKEN_ID: "my-root-key"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8201"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/logs
      - vault-data:/vault/file

volumes:
  vault-data:
