name: vault
services:
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    command: "server"
    cap_add:
      - IPC_LOCK
    volumes:
      - ../data/vault/data:/vault/data
